/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { EbubeStake } from "./EbubeStake";
export type { EbubeToken } from "./EbubeToken";
export type { IEbubeToken } from "./IEbubeToken";
export type { IPeteToken } from "./IPeteToken";
export type { PeteStake } from "./PeteStake";
export type { PeteToken } from "./PeteToken";
