/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface TicketFactoryInterface extends Interface {
  getFunction(
    nameOrSignature: "createTicketContract" | "organizerTickets"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "TicketContractCreated"): EventFragment;

  encodeFunctionData(
    functionFragment: "createTicketContract",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "organizerTickets",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "createTicketContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "organizerTickets",
    data: BytesLike
  ): Result;
}

export namespace TicketContractCreatedEvent {
  export type InputTuple = [
    eventOrganizer: AddressLike,
    ticketContract: AddressLike
  ];
  export type OutputTuple = [eventOrganizer: string, ticketContract: string];
  export interface OutputObject {
    eventOrganizer: string;
    ticketContract: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TicketFactory extends BaseContract {
  connect(runner?: ContractRunner | null): TicketFactory;
  waitForDeployment(): Promise<this>;

  interface: TicketFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createTicketContract: TypedContractMethod<
    [_name: string, _symbol: string],
    [string],
    "nonpayable"
  >;

  organizerTickets: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createTicketContract"
  ): TypedContractMethod<
    [_name: string, _symbol: string],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "organizerTickets"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  getEvent(
    key: "TicketContractCreated"
  ): TypedContractEvent<
    TicketContractCreatedEvent.InputTuple,
    TicketContractCreatedEvent.OutputTuple,
    TicketContractCreatedEvent.OutputObject
  >;

  filters: {
    "TicketContractCreated(address,address)": TypedContractEvent<
      TicketContractCreatedEvent.InputTuple,
      TicketContractCreatedEvent.OutputTuple,
      TicketContractCreatedEvent.OutputObject
    >;
    TicketContractCreated: TypedContractEvent<
      TicketContractCreatedEvent.InputTuple,
      TicketContractCreatedEvent.OutputTuple,
      TicketContractCreatedEvent.OutputObject
    >;
  };
}
