/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as ierc721Sol from "./IERC721.sol";
export { ClassRegistration__factory } from "./ClassRegistration__factory";
export { IPeteToken__factory } from "./IPeteToken__factory";
export { PeteNFT__factory } from "./PeteNFT__factory";
export { PeteToken__factory } from "./PeteToken__factory";
export { PiggyBank__factory } from "./PiggyBank__factory";
export { PiggyBankSafekeep__factory } from "./PiggyBankSafekeep__factory";
export { Savings__factory } from "./Savings__factory";
