/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as ierc721Sol from "./IERC721.sol";
export type { ierc721Sol };
export type { ClassRegistration } from "./ClassRegistration";
export type { IPeteToken } from "./IPeteToken";
export type { PeteNFT } from "./PeteNFT";
export type { PeteToken } from "./PeteToken";
export type { PiggyBank } from "./PiggyBank";
export type { PiggyBankSafekeep } from "./PiggyBankSafekeep";
export type { Savings } from "./Savings";
