/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as ercTSol from "./ErcT.sol";
export type { ercTSol };
export type { IERC20 } from "./IERC20";
export * as factories from "./factories";
export type { ERC20 } from "./ErcT.sol/ERC20";
export { ERC20__factory } from "./factories/ErcT.sol/ERC20__factory";
export { IERC20__factory } from "./factories/IERC20__factory";
